### ISSUE TITLE
色々と更新して、正常な状態にする

### ISSUE THREAD

**Issue by tomii9273** [tomii9273/atcoder_type_checker#2]
## WHY
1年近く更新が滞っており、バグもあり、このままではまずいため

## WHAT
- [x] develop ブランチ作成 (以降の内容は、基本一つずつPRを作って行い、develop ブランチにマージする) 
  - 順番自由
    - [x] バグ修正 (スコア2100点がノーカウント): #12
    - [x] unrated コンテストの結果を含めないようにする: #12
    - [x] ~~別のフォルダにあるコードなどをこちらに移動~~ #3 で実施済
  - 順番指定
    - [x] 最新コンテストまでのデータを追加 (誤って main に直接マージしてしまった → 一旦 revert → #13 で再コミット)
    - [x] 見つかったバグ修正: #14
    - [x] 上記を反映して補正値を再計算: #15
    - [x] 告知文など見える部分の更新: #16
    - [x] #18
    - [x] ちゃんと動くか確認
- [x] develop ブランチを main にマージ: #17
  - develop ブランチは残しておき、今後も大規模な変更を行う際は develop から切る
- [x] https://atcoder-type-checker.herokuapp.com/ から動くことを確認
  - 表示されない (デプロイには成功しているように見える)
  - 手動で github の main を heroku の main に反映 → 表示されず

### エラー解決

`heroku logs` → `Error: Missing required flag` が出る
https://qiita.com/hirokik-0076/items/71c104158fa8b963ba85 を見ると、heroku と github が紐づいていないときに出るようだったので、`heroku git:remote -a atcoder-type-checker` を実行→`git remote -v` で紐づいたことを確認
`git push heroku main` → デプロイできたが、まだ表示されない
`heroku logs` → エラー箇所が表示された
#19 で修正 → 正常に動いた！

参考: https://qiita.com/ryonishimura37/items/b72ecc829f9501857528

### 告知ツイート
https://twitter.com/Tomii9273/status/1565970225321095168?s=20&t=ep_oACd5VSmUHNrqp60_5A
